### ISSUE TITLE
Upgrade to CircleCI 2

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#207]

**Comment by looztra** [comment]
I had a first look at this.

In CircleCI2, everything runs in a container, so for the deploy stage we have 2 solutions (at least) :

- keep the same principles as our circle1 deploy stage, hence we need to build a custom image with npm+gcloud so that we can still use `npm run deploy`
- replace `deploy.js` by a shell calls and we can use a (more?) simple image with only `gcloud` (like https://hub.docker.com/r/google/cloud-sdk/ for instance)

Question : is there a specific reason why we are pinning the gcloud sdk to version `135.0.0`? (ping @jlandure @hgwood )

At a first glance, I'd favour using  a `gcloud sdk` only image + shell script :

- because I'd prefer not having to build a `gcloud sdk+node` image
- certainly because I'm not a js folk and hence I don't see what features bring `npm` compared to a shell script in this use case [mixed with CircleCI 2 as the build orchestrator] (it maybe only a matter of point of view obviously)

**Comment by hgwood** [comment]
I agree.

As for the gcloud version pinning, if I remember correctly it is simply so that the build is stable. The version may be changed.

**Comment by looztra** [comment]
Ok, I'll try to provide a circle ci 2 descriptor while working on the "devops-mindset-tooling" training (previously "devops for java". Stay tuned :-)

**Comment by hgwood** [comment]
Done, see https://github.com/Zenika/Formation--Modele/pull/135
